CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  isAdmin BOOLEAN DEFAULT 0
);

CREATE TABLE IF NOT EXISTS bingos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  prize TEXT NOT NULL,
  status TEXT NOT NULL,
  drawnNumbers TEXT,
  winner INTEGER
);

CREATE TABLE IF NOT EXISTS cards (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  bingoId INTEGER NOT NULL,
  userId INTEGER NOT NULL,
  numbers TEXT,
  markedNumbers TEXT,
  FOREIGN KEY (bingoId) REFERENCES bingos(id),
  FOREIGN KEY (userId) REFERENCES users(id)
);